
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, ... }:

{
  time.timeZone = "Africa/Kinshasa";

  settings = {
    network.host_name = "benuc036";
    boot.mode = "uefi";
    reverse_tunnel.enable = true;
    crypto.encrypted_opt.enable = true;
    docker.enable = true;
  };

#  systemd = with lib; {
#    automounts = [
#      {
#        enable = true;
#        description = "Automount the PACS storage directory.";
#        where = "/run/pacs";
#        wantedBy  = [ "multi-user.target" ];
#      }
#    ];
#
#    mounts = let
#      dependent_services = (optional config.virtualisation.docker.enable "docker.service");
#    in [
#      {
#        enable = true;
#        where = "/run/pacs";
#        what = "//nestor/PACS";
#        type = "cifs";
#        options = "rw,credentials=/opt/bahmni_cifs,vers=3,soft,iocharset=utf8,uid=1023,gid=1023,dir_mode=0775,file_mode=0775";
#        after = [ "network-online.target" ];
#        requires = [ "network-online.target" ];
#        before = dependent_services;
#        requiredBy = dependent_services;
#      }
#    ];
#  };

}

