
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ lib, ...}:

with lib;

{

  time.timeZone = "Europe/Brussels";

  settings = {
    network.host_name = "benuc012";
    boot.mode = "uefi";
    reverse_tunnel.enable = true;
    crypto.encrypted_opt.enable = true;
    docker.enable = true;
  };

  networking = {
    firewall = {
      allowedTCPPorts = [ 1234 ];
      extraCommands = ''
        function append_rule() {
          append_rule4 "''${1}"
          append_rule6 "''${1}"
        }

        function append_rule4() {
          do_append_rule "''${1}" "iptables"
        }

        function append_rule6() {
          do_append_rule "''${1}" "ip6tables"
        }

        function do_append_rule() {
          rule="''${1}"
          iptables="''${2}"
          if [ $(''${iptables} -C ''${rule} 2>/dev/null; echo $?) -ne "0" ]; then
            ''${iptables} -A ''${rule}
          fi
        }

        # Forward all outgoing traffic on the bridge belonging to existing connections
        append_rule  "FORWARD --out-interface br0 --match conntrack --ctstate ESTABLISHED,RELATED --jump ACCEPT"
        # Accept all outgoing traffic to the external interface of the bridge
        append_rule  "FORWARD --out-interface br0 --match physdev --physdev-out enp1s0 --jump ACCEPT"
        # Accept DHCPv4
        append_rule4 "FORWARD --out-interface br0 --protocol udp --dport 67:68 --sport 67:68 --jump ACCEPT"
        # IPv6 does not work without ICMPv6
        append_rule6 "FORWARD --out-interface br0 --protocol icmpv6 --jump ACCEPT"
        # DROP by default
        ip46tables --policy FORWARD DROP
      '';
    };
    useDHCP = mkForce false;
    bridges.br0.interfaces = [ "enp1s0" "enp2s0" ];
    interfaces.br0.useDHCP = true;
  };

}

