
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{

  time.timeZone = "Africa/Freetown";

  settings = {
    network.host_name = "benuc026";
    boot = {
      mode = "legacy";
      device = "/dev/disk/by-id/wwn-0x502b2a201d1c1b1a";
    };
    reverse_tunnel.enable = true;
    crypto = {
      enable = true;
      device = "/safe.img";
    };
    docker.enable = true;
    users.users = {
      yusuph.enable = true;
      damien.enable = true;
      didier.enable = true;
      joana.enable  = true;
      kathy.enable  = true;
      pasquale.enable  = true;
      godfried.enable = true;
      vini.enable = true;
      uf_sl_kenema = true;
    };
  };

}

