
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{
  time.timeZone = "Europe/Brussels";

  settings = {
    network.host_name = "benuc005";
    boot = {
      mode = "legacy";                                                                                                                            │···························
      device = "/dev/disk/by-id/ata-TS128GSSD420I_D675520211";
    };
    reverse_tunnel.enable = true;
    crypto.enable = false;
    docker.enable = true;
  };

}

