
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{
  time.timeZone = "Europe/Brussels";

  settings = {
    boot.mode = "uefi";
    reverse_tunnel.enable = true;
    crypto.encrypted_opt.enable = true;
    docker.enable = true;
    network = {
      host_name = "benuc013";
      static_ifaces.enp0s31f6 = {
        address = "10.210.210.13";
        prefix_length = 24;
        gateway = "10.210.210.254";
        nameservers = [ "9.9.9.9" "149.112.112.112" ];
      };
    };
  };
}

