########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

let
  statdPort  = 4000;
  lockdPort  = 4001;
  mountdPort = 4002;
in {
  time.timeZone = "Europe/Brussels";

  settings = {
    boot.mode = "uefi";
    reverse_tunnel.enable = true;
#    crypto.mounts = {
#     "es_proxy" = {
#
#     };
#    };
    vmware = {
      enable = true;
      inDMZ = true;
    };
    network = {
      host_name = "diggr-nfs";
      static_ifaces.ens192 = {
        address = "192.168.50.244";
        prefix_length = 24;
        gateway = "192.168.50.1";
        fallback = false;
      };
    };
  };

  services.nfs.server = {
    enable = true;
    exports = ''
      /opt  192.168.50.158(rw,nohide,insecure,no_subtree_check)
    '';
    inherit statdPort lockdPort mountdPort;
  };
  networking.firewall = let
    ports = [ 111 2049 statdPort lockdPort mountdPort ];
  in {
    allowedTCPPorts = ports;
    allowedUDPPorts = ports;
  };
}

