########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ pkgs, ... }:

{
  time.timeZone = "Europe/Brussels";

  boot.kernel.sysctl = {
    # Required for ElasticSearch
    "vm.max_map_count" = 262144;
  };

  settings = {
    boot.mode = "uefi";
    reverse_tunnel.enable = true;
    crypto.encrypted_opt.enable = true;
    vmware = {
      enable = true;
      inDMZ = true;
    };
    docker.enable = true;
    docker.swarm.enable = true;
    packages.python_package =
      (pkgs.python3.withPackages (python_pkgs: [
        python_pkgs.docker
      ]));
    network = {
      host_name = "docker-dmz-11";
      static_ifaces.ens192 = {
        address = "192.168.50.243";
        prefix_length = 24;
        gateway = "192.168.50.1";
        fallback = false;
      };
    };
  };
}

