
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{
  time.timeZone = "Europe/Brussels";

  settings = {
    boot.mode = "uefi";
    reverse_tunnel.enable = true;
    crypto.encrypted_opt = {
      enable = true;
      device = "/dev/LVMVolGroup_slow/nixos_data";
    };
    vmware.enable = true;
    docker.enable = true;
    network = {
      host_name = "nixos-dev";
      static_ifaces.ens160 = {
        address = "172.16.0.75";
        prefix_length = 16;
        gateway = "172.16.0.100";
        fallback = false;
      };
    };
  };
}

