
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, pkgs, ... }:

{
  time.timeZone = "Europe/Brussels";

  settings = {
    boot.mode = "uefi";
    reverse_tunnel.enable = true;
    crypto.encrypted_opt.enable = true;
    vmware = {
      enable = true;
      inDMZ = true;
    };
    docker.enable = true;
    service.traefik = {
      enable = true;
      network_name = "web";
    };
    network = {
      host_name = "sherlog-helpdesk";
      static_ifaces.ens192 = {
        address = "192.168.50.154";
        prefix_length = 24;
        gateway = "192.168.50.1";
        fallback = false;
      };
    };
  };

  systemd.services = {
    update_osticket_config = let
      osticket_dir = "/opt/osticket";
      osticket_config_dir = "${osticket_dir}/osticket-config";
    in {
      serviceConfig.Type = "oneshot";
      environment = let
        inherit (config.settings.reverse_tunnel) private_key;
      in {
        GIT_SSH_COMMAND = "${pkgs.openssh}/bin/ssh " +
                          "-i ${private_key} " +
                          "-o IdentitiesOnly=yes " +
                          "-o StrictHostKeyChecking=yes";
      };
      script = ''
          ${pkgs.git}/bin/git -C ${osticket_config_dir} fetch origin master
          ${pkgs.git}/bin/git -C ${osticket_config_dir} checkout master
          ${pkgs.git}/bin/git -C ${osticket_config_dir} reset --hard origin/master
          ${pkgs.git}/bin/git -C ${osticket_config_dir} clean -d --force
          ${pkgs.git}/bin/git -C ${osticket_config_dir} pull

          ${pkgs.docker-compose}/bin/docker-compose --project-directory ${osticket_dir} \
                                                    --file ${osticket_dir}/docker-compose.yml \
                                                    --no-ansi \
                                                    restart
      '';
    };
  };
}

