
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{

  time.timeZone = "Europe/Brussels";

  settings = {
    network.host_name = "sshrelay2";
    boot.separate_partition = false;
    reverse_tunnel.relay.enable = true;
    services.panic_button = {
      enable = true;
      armed  = false;
    };
  };

  swapDevices = [
    {
      device = "/swap.img";
      size   = 4096;
      randomEncryption.enable = true;
    }
  ];

  imports = [
    ../../modules/aws.nix
  ];

}

