
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ lib, ... }:

{

  settings.reverse_tunnel = {
    relay_servers = {
      sshrelay1.host = "sshrelay1.msf.be";
      sshrelay2.host = "sshrelay2.msf.be";
      sshrelay1-ip = { host = "185.199.180.11"; ip_tunnel = true; };
      sshrelay2-ip = { host = "15.188.17.148";  ip_tunnel = true; };
    };
    tunnels = {
      benuc002 = {
        remote_forward_port = 6002;
        public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA3YY2F1iOlm/7w9dSXzHU6ZbOuUx9oMwpfi5xFm6jrz";
      };
      rescue_iso = {
        remote_forward_port = 8000;
        public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDPkVmtj3Jkh/8tLJP+tE0/t3GMWJj6mVQ/PfkF7wIL6";
      };
    };
  };

  # python3 -c 'import crypt,getpass; print(crypt.crypt(getpass.getpass(), crypt.mksalt(crypt.METHOD_SHA512)))'
  users.users.msfocb.hashedPassword = lib.mkDefault
    "$6$FLtTyAhwtSyaTU1T$tnDBA5S5YeUF/UdO2KZtCVNieUlKGlL4iyGYtVKPI3Vfbyiu1BIH2j.BcScXPZbBbZ1P9PwKKh5B7lNoPr9o31";

}

