
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ lib, ... }:

{
  
  settings.reverse_tunnel.relay_servers = [
    { name = "google";     host = "msfrelay1.msfict.info"; }
    { name = "ixelles";    host = "ehealthsshrelayhq1.msf.be"; }
    { name = "ixelles-ip"; host = "194.78.17.132"; port_prefix = 1; }
  ];

  # python3 -c 'import crypt,getpass; print(crypt.crypt(getpass.getpass(), crypt.mksalt(crypt.METHOD_SHA512)))'
  users.extraUsers.msfocb.hashedPassword = lib.mkDefault
    "$6$FLtTyAhwtSyaTU1T$tnDBA5S5YeUF/UdO2KZtCVNieUlKGlL4iyGYtVKPI3Vfbyiu1BIH2j.BcScXPZbBbZ1P9PwKKh5B7lNoPr9o31";

}

