
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ ... }:

{

  settings.users = let

    admin = {
      enable = true;
      extraGroups = [ "wheel" "docker" ];
      hasShell = true;
      canTunnel = true;
    };
    tunnelOnly = {
      hasShell = false;
      canTunnel = true;
    };

  in {

    ramses   = admin;
    msg      = admin;
    thierry  = admin;
    mohammad = admin;

    damien   = tunnelOnly;
    didier   = tunnelOnly;
    dirk     = tunnelOnly;
    godfried = tunnelOnly;
    joana    = tunnelOnly;
    kathy    = tunnelOnly;
    # IHS Informatics consultant for Bahmni
    wasim    = tunnelOnly;
    yusuph   = tunnelOnly // {
      extraGroups = [ "docker" ];
      hasShell = true;
    };

  };

  # Only user with a password, but not usable via SSH.
  # To be used for console access in case of emergencies.
  users.extraUsers.msfocb = {
    isNormalUser = true;
    extraGroups = [ "wheel" ];
    hashedPassword = (import ./global_settings.nix).admin_user_hashedPassword;
    openssh.authorizedKeys.keyFiles = [];
  };

}

