
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{
  settings.reverse_tunnel = {
    relay_servers = {
      sshrelay1.addresses = [ "sshrelay1.msf.be" "185.199.180.11" ];
      sshrelay2.addresses = [ "sshrelay2.msf.be" "15.188.17.148"  ];
    };
  };
}

