
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{
  settings.reverse_tunnel = {
    relay_servers = {
      sshrelay1.host = "sshrelay1.msf.be";
      sshrelay2.host = "sshrelay2.msf.be";
      sshrelay1-ip = { host = "185.199.180.11"; ip_tunnel = true; };
      sshrelay2-ip = { host = "15.188.17.148";  ip_tunnel = true; };
    };
  };
}

