
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ lib, ... }:

with lib;

{
  imports = [
    ./ocb_tunnels.nix
    ./ocb_users.nix
  ];
  settings.system.nix_channel = mkDefault "19.09";
}

