
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{
  time.timeZone = "Europe/Paris";

  settings = {
    network.host_name = "aws_staging";
    reverse_tunnel.enable = true;
    docker.enable = true;
  };

  imports = [
    ../modules/aws.nix
  ];
}

