
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ pkgs, ...}:

{

  networking.hostName = "aws_staging";
  time.timeZone = "Europe/Paris";

  settings = {
reverse_tunnel = {
      enable = true;
      remote_forward_port = 7070;
    };
    docker.enable = true;
  };

  imports = [
    ../modules/aws.nix
  ];

}

