
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{
  networking.hostName = "benuc037";
  time.timeZone = "Africa/Nairobi";

  settings = {
    boot.mode = "uefi";
    reverse_tunnel.enable = true;
    crypto.enable = true;
    docker.enable = true;
    
    users.users = {
      yusuph.enable = true;
      damien.enable = true;
      didier.enable = true;
      joana.enable  = true;
      kathy.enable  = true;
      pasquale.enable  = true;
      godfried.enable = true;
      vini.enable = true;
    };    
  };

}
