########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ pkgs, ...}:

{

  time.timeZone = "Europe/Brussels";

  settings = {
    boot.mode = "uefi";
    reverse_tunnel.enable = true;
    crypto = {
      enable = true;
    };
    docker.enable = true;
  };

  networking = {
    hostName = "benuc013";
    nameservers = [ "9.9.9.9" "149.112.112.112" ];
    interfaces.enp0s31f6 = {
      useDHCP = false;
      ipv4.addresses = [ { address = "10.210.210.13"; prefixLength = 24; } ];
    };
    defaultGateway.address = "10.210.210.254";
  };

}
