
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{
  networking.hostName = "benuc013";
  time.timeZone = "Africa/Kinshasa";

  settings = {
    boot = {
      mode = "legacy";
      device = "/dev/disk/by-id/ata-TS128GMTS600_D274641630";
    };
    reverse_tunnel = {
      enable = true;
      remote_forward_port = 6013;
    };
    crypto.enable = false;
    docker.enable = false;
  };

}

