
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{
  hostname = "benuc009";
  imports = [
    ../docker.nix
    ../users/yusuph.nix
  ];

  boot = {
    # Set to either "legacy" or "uefi" depending on how you install the system
    mode = "uefi";
    # Set to "nodev" for an uefi system.
    device = "nodev";
  };

  # Timezone of the location where the server will be deployed
  timezone = "Africa/Nairobi";
  reverse_tunnel = {
    enabled = true;
    forward_port = "6009";
  };
  crypto = {
    enabled = true;
    encrypted_device = "/safe.img";
  };

}

