
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{
  networking.hostName = "benuc005";
  time.timeZone = "Europe/Brussels";

  settings = {
    boot = {
      mode = "legacy";                                                                                                                            │···························
      device = "/dev/disk/by-id/ata-TS128GSSD420I_D675520211";
    };
    reverse_tunnel = {
      enable = true;
      remote_forward_port = 6005;
    };
    crypto.enable = false;
    docker.enable = true;
  };

}

