
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{
  hostname = "benuc021";
  imports = [
    ../bahmni.nix
  ];

  boot = {
    # Set to either "legacy" or "uefi" depending on how you install the system
    mode = "legacy";
    # Set to "nodev" for an uefi system.
    device = "/dev/disk/by-id/wwn-0x502b2a201d1c1b1a";
  };

  # Timezone of the location where the server will be deployed
  timezone = "Asia/Karachi";
  reverse_tunnel = {
    enabled = true;
    forward_port = "6021";
  };
  crypto = {
    enabled = true;
    encrypted_device = "/safe.img";
  };

}

