
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{
  hostname = "chk-emr-a";
  imports = [
    ../bahmni.nix
  ];

  boot = {
    # Set to either "legacy" or "uefi" depending on how you install the system
    mode = "legacy";
    # Set to "nodev" for an uefi system.
    device = "/dev/disk/by-id/wwn-0x5000c500935b35ec";
  };

  # Timezone of the location where the server will be deployed
  timezone = "Africa/Kinshasa";
  reverse_tunnel = {
    enabled = true;
    forward_port = "7000";
  };
  crypto = {
    enabled = true;
    encrypted_device = "/dev/LVMVolGroup/nixos_data";
  };

}

