
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{

  networking.hostName = "nixos-dev-xl";
  time.timeZone = "Europe/Brussels";

  settings = {
    boot = {
      mode = "legacy";
      device = "/dev/disk/by-path/pci-0000:03:00.0-scsi-0:0:0:0";
      separate_partition = false;
    };
    reverse_tunnel = {
      enable = true;
      remote_forward_port = 7030;
    };
    crypto = {
      enable = true;
      device = "/dev/LVMVolGroup/nixos_data";
    };
  };

  imports = [
    ../vmware.nix
    ../local/static-network.nix
    ../bahmni.nix
    ../docker-registry.nix
    ../ansible.nix
    ../nixops.nix
  ];

}

