
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ ... }:

{
  users.extraUsers.msg = {
    extraGroups = [ "wheel" "docker" ];
    hasShell = true;
    canTunnel = true;
  };
}

