name: NixOS build and deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'install.sh'
      - 'rescue_iso/**'
      - 'README.md'
      - '.gitignore'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        group_id: [ 1, 2, 3, 4 ]
    steps:
      - uses: 'actions/checkout@v2'
      - uses: cachix/install-nix-action@master
        with:
          nix_path: nixpkgs=channel:nixos-20.03
      - name: 'build.sh with group id ${{ matrix.group_id }}'
        run: './.github/actions/nixos_build/build.sh'
        with:
          nixos_build_groups: 4
          nixos_build_group_id: ${{ matrix.group_id }}
  deploy:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - uses: 'msf-ocb/nixos-deploy@master'
        with:
          nixos_robot_key: '${{ secrets.NIXOS_ROBOT_KEY }}'
          nixos_deploy_fixed_hosts: 'sshrelay1.msf.be sshrelay2.msf.be'
          nixos_deploy_service: 'nixos_rebuild_config.service'

