name: NixOS build and deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'install.sh'
      - 'rescue_iso/**'
      - 'README.md'
      - '.gitignore'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: './.github/actions/nixos_build'
        env:
          NIXOS_CHANNEL: 'nixos-20.03'
  deploy:
    needs: build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'msf-ocb/nixos-deploy@master'
        env:
          NIXOS_ROBOT_KEY: '${{ secrets.NIXOS_ROBOT_KEY }}'
          NIXOS_DEPLOY_FIXED_HOSTS: 'sshrelay1.msf.be sshrelay2.msf.be'
          NIXOS_DEPLOY_SERVICE: 'nixos_rebuild_config.service'

