name: NixOS build and deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'install.sh'
      - 'rescue_iso/**'
      - 'README.md'
      - '.gitignore'

jobs:
  build_1:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: './.github/actions/nixos_build'
        with:
          nixos_build_groups: 4
          nixos_build_group_id: 1
  build_2:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: './.github/actions/nixos_build'
        with:
          nixos_build_groups: 4
          nixos_build_group_id: 2
  build_3:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: './.github/actions/nixos_build'
        with:
          nixos_build_groups: 4
          nixos_build_group_id: 3
  build_4:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: './.github/actions/nixos_build'
        with:
          nixos_build_groups: 4
          nixos_build_group_id: 4
  deploy:
    needs:
      - build_1
      - build_2
      - build_3
      - build_4
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'msf-ocb/nixos-deploy@master'
        with:
          nixos_robot_key: '${{ secrets.NIXOS_ROBOT_KEY }}'
          nixos_deploy_fixed_hosts: 'sshrelay1.msf.be sshrelay2.msf.be'
          nixos_deploy_service: 'nixos_rebuild_config.service'

