---

name: 'NixOS build'

on:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: './.github/actions/nixos_build'
        env:
          NIXOS_CHANNEL: 'nixos-20.03'

