name: NixOS build and deploy

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'install.sh'
      - 'scripts/**'
      - 'rescue_iso/**'
      - 'README.md'
      - '.gitignore'
      - '.github/workflows/build_iso.yml'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        group_id: [ 0, 1, 2, 3 ]
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'cachix/install-nix-action@master'
        with:
          nix_path: 'nixpkgs=channel:nixos-20.03'
      - uses: cachix/cachix-action@master
        with:
          name: 'panic-button'
          skipPush: true
      - run: './.github/scripts/build.py --group_amount 4 --group_id ${{ matrix.group_id }}'
  deploy:
    runs-on: 'ubuntu-latest'
    needs: build
    steps:
      - uses: 'msf-ocb/nixos-deploy@master'
        with:
          nixos_robot_key: '${{ secrets.NIXOS_ROBOT_KEY }}'
          nixos_deploy_fixed_hosts: 'sshrelay1.msf.be sshrelay2.msf.be'
          nixos_deploy_service: 'nixos_rebuild_config.service'

