name: NixOS build and deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'install.sh'
      - 'rescue_iso/**'
      - 'README.md'
      - '.gitignore'

defaults:
  runs-on: 'ubuntu-latest'

jobs:
  build:
    strategy:
      matrix:
        group_id: [ 1, 2, 3, 4 ]
    steps:
      - uses: 'actions/checkout@v2'
      - uses: './.github/actions/nixos_build'
        with:
          nixos_build_groups: 4
          nixos_build_group_id: ${{ matrix.group_id }}
  deploy:
    needs: build
    steps:
      - uses: 'msf-ocb/nixos-deploy@master'
        with:
          nixos_robot_key: '${{ secrets.NIXOS_ROBOT_KEY }}'
          nixos_deploy_fixed_hosts: 'sshrelay1.msf.be sshrelay2.msf.be'
          nixos_deploy_service: 'nixos_rebuild_config.service'

