---

name: 'NixOS Rescue ISO build'

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'org-spec/hosts/'
      - 'install.sh'
      - 'README.md'
      - '.gitignore'

jobs:
  build_iso:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'cachix/install-nix-action@master'
        with:
          nix_path: 'nixpkgs=channel:nixos-20.03'
      - run: 'touch ./local/id_tunnel_iso && ./rescue_iso/build_iso.sh'

