name: NixOS build and deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'install.sh'
      - 'rescue_iso/**'
      - 'README.md'
      - '.gitignore'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: './.github/actions/nixos_build'
  deploy:
    needs: build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'msf-ocb/nixos-deploy@master'
        with:
          nixos_robot_key: '${{ secrets.NIXOS_ROBOT_KEY }}'
          nixos_deploy_fixed_hosts: 'sshrelay1.msf.be sshrelay2.msf.be'
          nixos_deploy_service: 'nixos_rebuild_config.service'

