name: NixOS deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'install.sh'
      - 'rescue_iso/**'
      - 'README.md'
      - '.gitignore'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@v2
    - uses: ./.github/actions/nixos_deploy
      env:
        VAULT_PASS: ${{ secrets.VAULT_PASS }}

